name = "ethereum-worker"
type = "webpack"
webpack_config = "webpack.config.js"

workers_dev = true
account_id = "e921f16c347adc83c0b29f1f758a860c"
zone_id = ""
route = ""
vars = { ORIGIN_URL = "https://infinite-ak-network-personals.trycloudflare.com" }
