apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  parity.toml: |-
  {{- include (print $.Template.BasePath "/_parity.toml") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
data:
  {{- (.Files.Glob "check_node_health.sh").AsConfig | nindent 2 }}
---
