apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    chain: eth
{{ include "parity.labels" . | indent 4 }}
spec:
  type:  {{ .Values.service.type }}
  ports:
  {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "parity.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
