apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "parity.fullname" . }}
  labels:
{{ include "parity.labels" . | indent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-service"
  replicas: {{ .Values.replicaCount }} # by default is 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "parity.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      parity/chain: {{ .Values.parity.chain }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "parity.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        parity/chain: {{ .Values.parity.chain }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if and .Values.externalLBp2p .Values.externalLBp2pIP }}
        args: ["--config=/config/parity.toml","--nat","extip:{{- .Values.externalLBp2pIP -}}"]
        {{ else }}
        args: ["--config=/config/parity.toml"]
        {{ end }}
        workingDir: "{{ .Values.parity.base_path }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
          {{- range $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
          name: "{{ $val.name }}"
          protocol: {{ $val.protocol | default "TCP" }}
          {{- end }}
        volumeMounts:
        - name: parity-config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
        - name: parity-pvc
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /scripts/check_node_health.sh
            - http://127.0.0.1:{{ .Values.service.rpcPort }}
            - "300"
            - last_synced_block.txt
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
      {{- if .Values.argo.enabled }}
      - name: argo-tunnel
        image: crazymax/cloudflared:2020.2.1
        imagePullPolicy: IfNotPresent
        command: ["cloudflared", "tunnel"]
        args:
        - --url=127.0.0.1:{{ .Values.service.rpcPort }}
        - --no-autoupdate
        {{- if .Values.argo.hostname }}
        - --hostname={{- .Values.argo.hostname -}}
        {{- end }}
        {{- if .Values.argo.certSecretName }}
        - --origincert=/etc/cloudflared/cert.pem
        {{- end }}
        {{- if .Values.argo.lbPool }}
        - --lb-pool {{ .Values.argo.lbPool }}
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 20Mi
        {{- if .Values.argo.certSecretName }}
        volumeMounts:
        - mountPath: /etc/cloudflared
          name: tunnel-secret
          readOnly: true
        {{- end }}
      {{- end }}
      volumes:
        - name: parity-config
          configMap:
            name: "{{ .Release.Name }}-config"
        - name: scripts
          configMap:
            name: "{{ .Release.Name }}-scripts"
        {{- if .Values.argo.certSecretName }}
        - name: tunnel-secret
          secret:
            secretName: {{ .Values.argo.certSecretName }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: parity-pvc
      spec:
        accessModes:
        - {{.Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        volumeMode: Filesystem
