[Eth]
NetworkId = {{ .Values.genesis.networkId }}
SyncMode = "fast"
LightPeers = 100

[Node]
# DataDir = "/root/.ethereum/testnet"
HTTPPort = 8545
HTTPModules = ["net", "web3", "eth"]
{{- if .Values.argo.hostname }}
HTTPCors = ["{{ .Values.argo.hostname }}"]
HTTPVirtualHosts = ["{{ .Values.argo.hostname }}"]
{{- else }}
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
{{- end }}
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLPort = 8547
GraphQLVirtualHosts = ["localhost"]
NoUSB = true

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
