apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethereum.fullname" . }}-geth-tx
  labels:
    app: {{ include "ethereum.name" . }}
    chart: {{ include "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ethereum.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "ethereum.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["geth"]
        args:
        - "--verbosity=3"
        - "--config=/config/geth.toml"
        {{- if eq .Values.genesis.networkId 3.0 }}
        - "--testnet"
        {{- end }}
        ports:
        - name: rpc
          containerPort: 8545
        - name: ws
          containerPort: 8546
        - name: discovery-udp
          containerPort: 30303
          protocol: UDP
        - name: discovery-tcp
          containerPort: 30303
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: config
          mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "ethereum.fullname" . }}-geth-config
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "ethereum.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
