apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethereum.fullname" . }}
  labels:
    app.kubernetes.io/app: {{ include "ethereum.name" . }}
    helm.sh/chart: {{ include "ethereum.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ include "ethereum.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ include "ethereum.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["geth"]
        args:
        - "--verbosity=3"
        - "--config=/config/geth.toml"
        - "--rpc"
        - "--ws"
        {{- if eq .Values.genesis.networkId 3.0 }}
        - "--testnet"
        {{- end }}
        ports:
        - name: rpc
          containerPort: {{ .Values.service.rpcPort }}
        - name: ws
          containerPort: {{ .Values.service.wsPort }}
        - name: discovery-tcp
          containerPort: {{ .Values.service.p2pPort }}
        - name: discovery-udp
          containerPort: {{ .Values.service.p2pPort }}
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: config
          mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "ethereum.fullname" . }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "ethereum.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
