apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ethereum.name" . }}
    helm.sh/chart: {{ include "ethereum.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "ethereum.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
    - name: discovery-tcp
      port: {{ .Values.service.p2pPort }}
      targetPort: discovery-tcp
    - name: discovery-udp
      port: {{ .Values.service.p2pPort }}
      targetPort: discovery-udp
      protocol: UDP
